services:
  db:
    image: postgres:13-alpine3.20
    restart: always
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: rai
      POSTGRES_USER: rai
      POSTGRES_PASSWORD: rai
volumes:
  db:
