"""file mappings

Revision ID: 0a4973108ab6
Revises: 1d6c10ba24fc
Create Date: 2025-05-26 03:00:15.940362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a4973108ab6'
down_revision: Union[str, None] = '1d6c10ba24fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_mappings_alias'), 'file_mappings', ['alias'], unique=False)
    op.create_index(op.f('ix_file_mappings_filename'), 'file_mappings', ['filename'], unique=False)
    op.create_table('ingested_file_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('file_mapping_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['file_mapping_id'], ['file_mappings.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ingested_file_mappings')
    op.drop_index(op.f('ix_file_mappings_filename'), table_name='file_mappings')
    op.drop_index(op.f('ix_file_mappings_alias'), table_name='file_mappings')
    op.drop_table('file_mappings')
    # ### end Alembic commands ###
