"""file mapping: add content-type

Revision ID: 17df3d6c4322
Revises: 644fb91ee960
Create Date: 2025-05-26 03:11:30.480799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17df3d6c4322'
down_revision: Union[str, None] = '644fb91ee960'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_mappings', sa.Column('content_type', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file_mappings', 'content_type')
    # ### end Alembic commands ###
