"""user-acct: activation_id: unique

Revision ID: 1d6c10ba24fc
Revises: 6c9a5afda25c
Create Date: 2025-05-25 18:54:11.197561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d6c10ba24fc'
down_revision: Union[str, None] = '6c9a5afda25c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_accounts_activation_id', table_name='user_accounts')
    op.create_index(op.f('ix_user_accounts_activation_id'), 'user_accounts', ['activation_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_accounts_activation_id'), table_name='user_accounts')
    op.create_index('ix_user_accounts_activation_id', 'user_accounts', ['activation_id'], unique=False)
    # ### end Alembic commands ###
