"""user accounts: is active field

Revision ID: 2cd8a1cf4f66
Revises: faf517fb3eb3
Create Date: 2025-05-18 23:21:36.618356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cd8a1cf4f66'
down_revision: Union[str, None] = 'faf517fb3eb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_accounts', sa.Column('is_activated', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_accounts', 'is_activated')
    # ### end Alembic commands ###
