"""user accounts: username index

Revision ID: 5c6cf0c802ca
Revises: 2cd8a1cf4f66
Create Date: 2025-05-18 23:22:49.220430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c6cf0c802ca'
down_revision: Union[str, None] = '2cd8a1cf4f66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_acct_username', 'user_accounts', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_acct_username', table_name='user_accounts')
    # ### end Alembic commands ###
