"""file mapping: get rid of alias

Revision ID: 644fb91ee960
Revises: 0a4973108ab6
Create Date: 2025-05-26 03:09:16.696067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '644fb91ee960'
down_revision: Union[str, None] = '0a4973108ab6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_file_mappings_alias', table_name='file_mappings')
    op.drop_column('file_mappings', 'alias')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_mappings', sa.Column('alias', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_index('ix_file_mappings_alias', 'file_mappings', ['alias'], unique=False)
    # ### end Alembic commands ###
