"""user-acct: activation_id

Revision ID: 6c9a5afda25c
Revises: 81f4ac859ebe
Create Date: 2025-05-25 14:53:48.006338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c9a5afda25c'
down_revision: Union[str, None] = '81f4ac859ebe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_accounts', sa.Column('activation_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_user_accounts_activation_id'), 'user_accounts', ['activation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_accounts_activation_id'), table_name='user_accounts')
    op.drop_column('user_accounts', 'activation_id')
    # ### end Alembic commands ###
