"""token index

Revision ID: 81f4ac859ebe
Revises: 5c6cf0c802ca
Create Date: 2025-05-23 12:46:13.932868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81f4ac859ebe'
down_revision: Union[str, None] = '5c6cf0c802ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_auth_tokens_token'), 'auth_tokens', ['token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auth_tokens_token'), table_name='auth_tokens')
    # ### end Alembic commands ###
